version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
      - ./database:/app/database
      - ./latex-templates:/app/latex-templates
      - ./logs:/app/logs
    environment:
      - DATABASE_URL=sqlite:///./database/ats_resume.db
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  db_data:
  uploads_data:
  logs_data: